### PR TITLE
Update .poggit.yml to enable submodule cloning

### PR DESCRIPTION
**Pull request by SOF3**

### CODE REVIEW

**Comment by SOF3** [comment]
Your plugin has been rejected because of this.
Submodule cloning is only enabled for directly pushed commits right now. Please merge this pull request to see a fixed build.

Disclaimer: I have not tested it :P This is the first plugin repo that has submodule cloning.

**Comment by SOF3** [comment]
I would also like to mention that Poggit does not encourage submission of plugins that auto-update from untrusted sources, such as your own websites, because this would create a loophole where users believe their plugins are reviewed while they are actually updated by the developer that doesn't require review from Poggit.
We will provide an API for checking updates very soon.

**Comment by SalmonDE** [comment]
@SOF3 Oh, I'm sorry for the circumstances. Is there some sort of "newsletter"/news page for poggit to subscribe to?

**Comment by SOF3** [comment]
@SalmonDE no. Or yes, watch the poggit/poggit repo on GitHub :D
We're still in beta, and not even the documentation is complete, much less newsletter ;)

**Comment by SalmonDE** [comment]
@SOF3 Can I submit the plugin again when I turn the updater just to a notificator?

**Comment by SOF3** [comment]
@SalmonDE sure. Just make sure it doesn't execute custom code.

**Pull request merged**
