### PR TITLE
Update to PocketMine-MP 5

### PR DESCRIPTION
**Pull request by Wertzui123**

### CODE REVIEW

**Comment by Aericio** [comment]
No other changes needed at all? o_O

**Comment by Wertzui123** [comment]
Nope, works perfectly fine for me

**Comment by note3crafter** [comment]
its works yes but one error i have

[16:37:31.107] [AsyncWorker#3 thread/CRITICAL]: Error: "Call to a member function getBody() on null" (EXCEPTION) in "/home/CyberCraft/plugins/TopVoter-master/src/SalmonDE/TopVoter/Tasks/QueryServerListTask" at line 26
--- Stack trace ---
  #0 pmsrc/src/scheduler/AsyncTask(84): SalmonDE\TopVoter\Tasks\QueryServerListTask->onRun()
  #1 (): pocketmine\scheduler\AsyncTask->run()
--- End of exception information ---
[16:37:31.153] [Server thread/CRITICAL]: RuntimeException: "Worker 3 crashed while running task SalmonDE\TopVoter\Tasks\QueryServerListTask#162497" (EXCEPTION) in "pmsrc/src/scheduler/AsyncPool" at line 223

Error getBody on Null... but wye this happend i dont know mhh

**Comment by Wertzui123** [comment]
Hm, are you sure you have provided a valid API key and your server is connected to the internet? As I already said, it works perfectly fine for me, and the error you're getting doesn't seem to be related to the API 5 update.

**Comment by Wertzui123** [comment]
Weird, I got the same error an hour or so ago as well, but (at least until now) only once and it still shows the top voters.

**Comment by note3crafter** [comment]
found this error... dns error on root server... lol that cause no connection to the website and it wile crashing...

**Comment by note3crafter** [comment]
yes, the error also occurs sometimes just like that... but this time it was because I rebooted the root server and reset a config file for the dns server and I therefore had no connection to the website... and that's why it came the crash... had it just like that from time to time

**Comment by Wertzui123** [comment]
I suppose the plugin could use some error handling and simply display something like "data couldn't be fetched", but that's out of scope for this PR.

**Comment by note3crafter** [comment]
PocketMine-MP Crash Dump Tue Jul 18 13:23:35 CEST 2023

PocketMine-MP version: 5.3.1 [Protocol 594]
Git commit: 250d18e41bb6fc671cbd2e3d2daaee2e06770b0f
PHP version: 8.1.20
OS: Linux, linux

Error: Worker 0 crashed while running task SalmonDE\TopVoter\Tasks\QueryServerListTask#242923
File: pmsrc/src/scheduler/AsyncPool
Line: 223
Type: RuntimeException
Backtrace:
#0 pmsrc/src/scheduler/AsyncPool(260): pocketmine\scheduler\AsyncPool->checkCrashedWorker(int 0, object SalmonDE\TopVoter\Tasks\QueryServerListTask#242923)
#1 pmsrc/src/scheduler/AsyncPool(235): pocketmine\scheduler\AsyncPool->collectTasksFromWorker(int 0)
#2 pmsrc/src/Server(1786): pocketmine\scheduler\AsyncPool->collectTasks()
#3 pmsrc/src/Server(1671): pocketmine\Server->tick()
#4 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#5 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[17] /home/CyberCraft/, string[25] /home/CyberCraft/plugins/)
#6 pmsrc/src/PocketMine(357): pocketmine\server()
#7 pmsrc(11): require(string[61] phar:///home/CyberCraft/PocketMine-MP.phar/src/PocketMine.php)

Code:
[214] 						break;
[215] 					}
[216] 				}
[217] 			}
[218] 			if($crashedTask !== null){
[219] 				$message = "Worker $workerId crashed while running task " . get_class($crashedTask) . "#" . spl_object_id($crashedTask);
[220] 			}else{
[221] 				$message = "Worker $workerId crashed for unknown reason";
[222] 			}
[223] 			throw new \RuntimeException($message);
[224] 		}
[225] 	}
[226] 
[227] 	/**
[228] 	 * Collects finished and/or crashed tasks from the workers, firing their on-completion hooks where appropriate.
[229] 	 *
[230] 	 * @throws \ReflectionException
[231] 	 * @return bool whether there are tasks left to be collected
[232] 	 */
[233] 	public function collectTasks() : bool{

and i become this error totaly random bruh but wye i dont know hmm

**Comment by Wertzui123** [comment]
> its works yes but one error i have
> 
> [16:37:31.107] [AsyncWorker#3 thread/CRITICAL]: Error: "Call to a member function getBody() on null" (EXCEPTION) in "/home/CyberCraft/plugins/TopVoter-master/src/SalmonDE/TopVoter/Tasks/QueryServerListTask" at line 26 --- Stack trace --- #0 pmsrc/src/scheduler/AsyncTask(84): SalmonDE\TopVoter\Tasks\QueryServerListTask->onRun() #1 (): pocketmine\scheduler\AsyncTask->run() --- End of exception information --- [16:37:31.153] [Server thread/CRITICAL]: RuntimeException: "Worker 3 crashed while running task SalmonDE\TopVoter\Tasks\QueryServerListTask#162497" (EXCEPTION) in "pmsrc/src/scheduler/AsyncPool" at line 223
> 
> Error getBody on Null... but wye this happend i dont know mhh

See #44

**Pull request merged**
